name: Run Selenium On GitHub Action
on:
  push:
    paths:
      - GoogleSheet.csv
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"     # Runs every day at 7:00 AM UTC
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed    
      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  
        
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Install pandas
        run: pip install pandas
      - name: Install requests
        run: pip install requests
      - name: Install beautifulsoup4
        run: pip install beautifulsoup4
      - name: Install pandas xlrd oopenpyxl
        run: pip install pandas xlrd openpyxl

      - name: Running the Python script
        run: python Selenium-Template.py


      - name: Move specific CSV files to target folder
        run: |
          # 使用條件將特定格式的 xls 移動到指定資料夾
          for file in *.xls; do
            if [[ $file == K*.xls ]]; then
              mv "$file" file/
            fi
          done
          
      - name: change file's type
        run: python change_xls_to_csv.py
      - name: uncode-html
        run: python html.py
        
        
      - name: Commit and Push The Results From Python Selenium Action
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git add file/*.xls
         git commit -m "GitHub Actions Results added"
         git push


         
